### ISSUE TITLE
Bug: NameError: name 'core' is not defined

### ISSUE THREAD

**Issue by zzzzzozzzzz** [nathom/streamrip#111]
## Bug Report
**Source**
Qobuz

**Current Behavior**
NameError: name 'core' is not defined

**Command(s) used:**

```bash
poetry run rip discover --list '...'
rip discover --list '...'
```

**Environment**

- `streamrip` version: 9a21b35 | v0.6.7
- Python version: 3.9
- OS: Linux

**Traceback**
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/streamrip/streamrip/cli.py", line 415, in main
    cli(obj={})
  File "/home/user/.cache/pypoetry/virtualenvs/streamrip-p_MgOIO3-py3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/streamrip-p_MgOIO3-py3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/user/.cache/pypoetry/virtualenvs/streamrip-p_MgOIO3-py3.9/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.cache/pypoetry/virtualenvs/streamrip-p_MgOIO3-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.cache/pypoetry/virtualenvs/streamrip-p_MgOIO3-py3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/streamrip-p_MgOIO3-py3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/streamrip/streamrip/cli.py", line 232, in discover
    if core.interactive_search(kwargs["list"], "qobuz", "featured"):
NameError: name 'core' is not defined

**Comment by fredericmalo** [comment]
Hello, 

same here: 

**Environment**

streamrip version: v0.6.7
Python version: 3.9
OS: Apple M1

**Stacktrace**

rip -u https://open.qobuz.com/album/006025378096                     
streamrip is up-to-date!
Logging into qobuz
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/rip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/cli.py", line 415, in main
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1646, in invoke
    super().invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/cli.py", line 117, in cli
    core.download()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/core.py", line 252, in download
    item.load_meta(**arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/tracklists.py", line 75, in load_meta
    resp = self.client.get(self.id, media_type="album")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/clients.py", line 198, in get
    resp = self._api_get(media_type, item_id=item_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/clients.py", line 281, in _api_get
    raise Exception(f'Error fetching metadata. "{response["message"]}"')
Exception: Error fetching metadata. "No result matching given argument"
frederic@M1 test % rip discover --list most-streamed                             
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/rip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/cli.py", line 415, in main
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/cli.py", line 232, in discover
    if core.interactive_search(kwargs["list"], "qobuz", "featured"):
NameError: name 'core' is not defined


Thanks !

**Comment by zzzzzozzzzz** [comment]
@nathom 

`dev` branch

**Traceback**
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/streamrip/rip/cli.py", line 422, in main
    cli(obj={})
  File "/home/user/.cache/pypoetry/virtualenvs/streamrip-p_MgOIO3-py3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/streamrip-p_MgOIO3-py3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/user/.cache/pypoetry/virtualenvs/streamrip-p_MgOIO3-py3.9/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.cache/pypoetry/virtualenvs/streamrip-p_MgOIO3-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.cache/pypoetry/virtualenvs/streamrip-p_MgOIO3-py3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/streamrip-p_MgOIO3-py3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/streamrip/rip/cli.py", line 231, in discover
    if core.interactive_search(kwargs["list"], "qobuz", "featured"):
  File "/home/user/streamrip/rip/core.py", line 617, in interactive_search
    from simple_term_menu import TerminalMenu
ModuleNotFoundError: No module named 'simple_term_menu'
```

**Comment by nathom** [comment]
@fredericmalo It seems that for the first error you have an invalid link.

**Comment by fredericmalo** [comment]
Oh sorry nathom, you're right

Without thinking, I was trying streamrip by copy/paste the example found on homepage : https://github.com/nathom/streamrip#example-usage

It works with a correct url. Thanks !

**Comment by fredericmalo** [comment]
Hello, 

Now I've tried: `rip discover --list 'best-sellers'` and failed on same error: 

```python
% rip discover --list 'best-sellers'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/rip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/cli.py", line 415, in main
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/cli.py", line 232, in discover
    if core.interactive_search(kwargs["list"], "qobuz", "featured"):
NameError: name 'core' is not defined
```

Could someone help me please ? Thanks !

**Comment by nathom** [comment]
Fixed in `v0.7`

**Comment by fredericmalo** [comment]
Perfect thanks ! :)

**Comment by zzzzzozzzzz** [comment]
@nathom 
Not fixed:
https://github.com/nathom/streamrip/issues/111#issuecomment-873027858

**Comment by zzzzzozzzzz** [comment]
@nathom 
please go to ds!
