### ISSUE TITLE
[FEATURE] Remove the 500 limit (with fix for qobuz-dl inside)

### ISSUE THREAD

**Issue by TH0MVS** [nathom/streamrip#482]
### Is the feature request related to a problem. Please describe it.

This issue have been already discussed on qobuz-dl and here :
https://github.com/nathom/streamrip/issues/419
https://github.com/nathom/streamrip/issues/392

Someone (a great guy!) pushed a fix on qobuz-dl and it work :
https://github.com/vitiko98/qobuz-dl/pull/236/files

I checked your script but what I understand, the way you fetch urls is different. Could please consider to implement this fix in your script ? It would be REALLY appreciated for labels.

### Describe the solution you would like.

Please implement this fix : https://github.com/vitiko98/qobuz-dl/pull/236/files

### Describe alternatives you've considered.

I tried to fetch all URLs from labels with more than 500 albums, in order to get an albums list, but I failed miserably :-(

**Comment by nathom** [comment]
Fixed in v2. You can use it now by installing the dev branch.

**Comment by Corto86** [comment]
Hi, as I was trying to download an album with 55 discs and 730 tracks and failed, I uninstalled stable version and reinstalled the dev version to complete the download. Unfortunatly, it's still failing and I just got 500 tracks and the cover.
